version: '3.8'

services:
  dispatcher:
    build: ./dispatcher
    ports:
      - "8080:8080"  # Solo el dispatcher es accesible desde el host
    environment:
      - PORT=8080

  worker1:
    build: ./server
    environment:
      - PORT=8080
      - CALLBACK_URL=http://dispatcher:8080/callback  # Nombre del servicio "dispatcher"

  worker2:
    build: ./server
    environment:
      - PORT=8080
      - CALLBACK_URL=http://dispatcher:8080/callback

  worker3:
    build: ./server
    environment:
      - PORT=8080
      - CALLBACK_URL=http://dispatcher:8080/callback